
-- SELECT MESTRE DE TODOS
SELECT * FROM maquina AS mp
JOIN cpu AS cp ON cp.fk_maquina = mp.id_maquina
WHERE cp.id_cpu = (SELECT cs.id_cpu FROM cpu AS cs WHERE cs.fk_maquina = (mp.id_maquina) ORDER BY cs.id_cpu DESC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY);

--  SELECT PARA PEGAR O ID DA ULTIMA CPU CADASTRADA PARA OBTER SEUS LOGS
--  TÁ PEGANDO * OS DADOS... DEVE RETORNAR APENAS O ID DA CPU..
SELECT * FROM cpu WHERE fk_maquina = (1)
ORDER BY id_cpu DESC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

--  SELECT PARA PEGAR O ID DO ULTIMO DISCO CADASTRADO PARA OBTER SEUS LOGS
--  TÁ PEGANDO * OS DADOS... DEVE RETORNAR APENAS O ID DO DISCO..
SELECT * FROM disco WHERE fk_maquina = (1)
ORDER BY id_disco DESC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

--  SELECT PARA PEGAR O ID DA ULTIMA MEMORIA CADASTRADA PARA OBTER SEUS LOGS
--  TÁ PEGANDO * OS DADOS... DEVE RETORNAR APENAS O ID DA MEMORIA..
SELECT * FROM memoria WHERE fk_maquina = (1)
ORDER BY id_memoria DESC
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY